import { useEffect, useRef, useState } from 'react';
import type { ChatMessage, ChatSession, SessionSummary } from '../shared/types';

function Sidebar({ items, active, onNew, onSelect }: { items: SessionSummary[]; active: string | null; onNew: () => void; onSelect: (id: string) => void }): JSX.Element { return <aside><div className="brand">ArnAIv</div><button className="new-chat" onClick={onNew}>＋ New chat</button><div className="sessions">{items.map((item) => <button className={`session ${active === item.id ? 'active' : ''}`} key={item.id} title={item.title} onClick={() => onSelect(item.id)}>{item.title}</button>)}</div></aside>; }
function Messages({ messages, generating }: { messages: ChatMessage[]; generating: boolean }): JSX.Element { const bottom = useRef<HTMLDivElement>(null); useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }); }, [messages, generating]); return <div className="messages">{messages.map((message) => <article className={`message ${message.role}`} key={message.id}><div className="role">{message.role === 'user' ? 'You' : 'ArnAIv'}</div><div className="content">{message.content}{generating && message.role === 'assistant' && !message.content && <span className="typing">Thinking</span>}</div></article>)}<div ref={bottom}/></div>; }
function Input({ disabled, onSend }: { disabled: boolean; onSend: (content: string) => void }): JSX.Element { const [value, setValue] = useState(''); const ref = useRef<HTMLTextAreaElement>(null); const submit = (): void => { const content = value.trim(); if (!content || disabled) return; setValue(''); onSend(content); requestAnimationFrame(() => ref.current?.focus()); }; return <div className="composer"><textarea ref={ref} aria-label="Message ArnAIv" value={value} disabled={disabled} placeholder="Message ArnAIv..." onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} /><button onClick={submit} disabled={disabled || !value.trim()}>Send</button></div>; }
function DesktopOnly(): JSX.Element { return <main className="desktop-only"><section><h1>ArnAIv is a desktop application</h1><p>Start it with <code>npm run dev</code> to open it in Electron. The browser preview cannot access local conversations or the protected OpenAI connection.</p></section></main>; }
export default function App(): JSX.Element { const api = window.arnAIv; return api ? <ElectronApp api={api} /> : <DesktopOnly />; }
function ElectronApp({ api }: { api: typeof window.arnAIv }): JSX.Element {
  const [items, setItems] = useState<SessionSummary[]>([]); const [session, setSession] = useState<ChatSession | null>(null); const [generating, setGenerating] = useState(false); const [error, setError] = useState('');
  const refresh = async (): Promise<void> => setItems(await api.sessions.list());
  useEffect(() => { void refresh().catch(() => setError('Unable to load previous conversations.')); const offChunk = api.chat.onChunk((event) => { setSession((current) => { if (!current || current.id !== event.sessionId) return current; const existing = current.messages.find((message) => message.id === event.messageId); const messages: ChatMessage[] = existing ? current.messages.map((message) => message.id === event.messageId ? { ...message, content: message.content + (event.content ?? '') } : message) : [...current.messages, { id: event.messageId, role: 'assistant', content: event.content ?? '', createdAt: new Date().toISOString() }]; return { ...current, messages }; }); }); const offComplete = api.chat.onComplete(() => { setGenerating(false); void refresh(); }); const offError = api.chat.onError((event) => { setGenerating(false); setError(event.error ?? 'Unable to generate a response.'); }); return () => { offChunk(); offComplete(); offError(); }; }, [api]);
  const select = async (id: string): Promise<void> => { if (generating) return; const loaded = await api.sessions.get(id); if (loaded) setSession(loaded); };
  const create = async (): Promise<void> => { if (generating) return; setError(''); setSession(await api.sessions.create()); await refresh(); };
  const send = async (content: string): Promise<void> => { if (!session) return; setError(''); setGenerating(true); setSession({ ...session, messages: [...session.messages, { id: crypto.randomUUID(), role: 'user', content, createdAt: new Date().toISOString() }] }); try { await api.chat.send({ sessionId: session.id, content }); } catch (reason: unknown) { setGenerating(false); setError(reason instanceof Error ? reason.message : 'Unable to send message.'); } };
  const messages = session?.messages ?? [];
  return <main><Sidebar items={items} active={session?.id ?? null} onNew={() => void create()} onSelect={(id) => void select(id)} /><section className="chat"><header><span>{generating ? 'ArnAIv is generating…' : 'ArnAIv'}</span></header>{error && <div className="error" role="alert">{error}</div>}{messages.length ? <Messages messages={messages} generating={generating} /> : <div className="empty">ArnAIv</div>}<Input disabled={!session || generating} onSend={(content) => void send(content)} /></section></main>;
}
